import React, { useState } from "react";
import { Youtube, Copy, Check, Hash, Tag, FileText, Sparkles } from "lucide-react";
import { YouTubeMetadata } from "../types";

interface MetadataViewerProps {
  metadata: YouTubeMetadata;
  onUpdateMetadata?: (metadata: YouTubeMetadata) => void;
}

export const MetadataViewer: React.FC<MetadataViewerProps> = ({
  metadata,
  onUpdateMetadata,
}) => {
  const [copiedSection, setCopiedSection] = useState<string | null>(null);
  const [title, setTitle] = useState(metadata.youtubeTitle);
  const [description, setDescription] = useState(metadata.youtubeDescription);
  const [tags, setTags] = useState(metadata.tags.join(", "));
  const [hashtags, setHashtags] = useState(metadata.hashtags.join(" "));

  const handleCopy = (text: string, sectionKey: string) => {
    navigator.clipboard.writeText(text);
    setCopiedSection(sectionKey);
    setTimeout(() => setCopiedSection(null), 2000);
  };

  const handleSave = () => {
    onUpdateMetadata?.({
      ...metadata,
      youtubeTitle: title,
      youtubeDescription: description,
      tags: tags.split(",").map((t) => t.trim()).filter(Boolean),
      hashtags: hashtags.split(/\s+/).map((h) => h.trim()).filter(Boolean),
    });
  };

  return (
    <div className="w-full max-w-5xl mx-auto py-6 px-4 sm:px-6">
      <div className="bg-slate-900/90 border border-slate-800 rounded-3xl p-6 sm:p-8 shadow-2xl backdrop-blur-xl space-y-6">
        {/* Header */}
        <div className="flex items-center justify-between pb-4 border-b border-slate-800">
          <div className="flex items-center gap-3">
            <div className="w-10 h-10 rounded-xl bg-red-600/10 border border-red-600/20 flex items-center justify-center">
              <Youtube className="w-5 h-5 text-red-500" />
            </div>
            <div>
              <h3 className="text-xl font-bold text-white tracking-tight">
                Automated YouTube & Social Metadata
              </h3>
              <p className="text-xs text-slate-400">
                SEO-optimized title, description, timestamps, and high-ranking tags generated by Gemini.
              </p>
            </div>
          </div>
          <span className="text-[11px] font-mono text-slate-400 bg-slate-950 px-3 py-1.5 rounded-xl border border-slate-800">
            {metadata.reelName}
          </span>
        </div>

        {/* 1. YouTube Title */}
        <div>
          <div className="flex items-center justify-between mb-2">
            <label className="text-xs font-bold uppercase tracking-wider text-slate-300 flex items-center gap-1.5">
              <Sparkles className="w-3.5 h-3.5 text-amber-400" />
              <span>Optimized Video Title</span>
            </label>
            <button
              onClick={() => handleCopy(title, "title")}
              className="text-xs text-rose-400 hover:text-rose-300 font-semibold flex items-center gap-1 cursor-pointer"
            >
              {copiedSection === "title" ? <Check className="w-3.5 h-3.5 text-emerald-400" /> : <Copy className="w-3.5 h-3.5" />}
              <span>{copiedSection === "title" ? "Copied!" : "Copy Title"}</span>
            </button>
          </div>
          <input
            type="text"
            value={title}
            onChange={(e) => setTitle(e.target.value)}
            onBlur={handleSave}
            className="w-full px-4 py-3 bg-slate-950/80 border border-slate-800 rounded-xl text-slate-100 font-semibold text-sm focus:outline-none focus:border-rose-500 transition-colors"
          />
        </div>

        {/* 2. YouTube Description */}
        <div>
          <div className="flex items-center justify-between mb-2">
            <label className="text-xs font-bold uppercase tracking-wider text-slate-300 flex items-center gap-1.5">
              <FileText className="w-3.5 h-3.5 text-blue-400" />
              <span>Description & Timestamps</span>
            </label>
            <button
              onClick={() => handleCopy(description, "desc")}
              className="text-xs text-rose-400 hover:text-rose-300 font-semibold flex items-center gap-1 cursor-pointer"
            >
              {copiedSection === "desc" ? <Check className="w-3.5 h-3.5 text-emerald-400" /> : <Copy className="w-3.5 h-3.5" />}
              <span>{copiedSection === "desc" ? "Copied!" : "Copy Description"}</span>
            </button>
          </div>
          <textarea
            rows={5}
            value={description}
            onChange={(e) => setDescription(e.target.value)}
            onBlur={handleSave}
            className="w-full px-4 py-3 bg-slate-950/80 border border-slate-800 rounded-xl text-slate-200 text-xs font-mono leading-relaxed focus:outline-none focus:border-rose-500 transition-colors resize-y"
          />
        </div>

        {/* 3. Tags & Hashtags Grid */}
        <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
          {/* Tags */}
          <div className="bg-slate-950/60 p-4 rounded-2xl border border-slate-800/80">
            <div className="flex items-center justify-between mb-2">
              <label className="text-xs font-bold uppercase tracking-wider text-slate-300 flex items-center gap-1.5">
                <Tag className="w-3.5 h-3.5 text-teal-400" />
                <span>YouTube Tags</span>
              </label>
              <button
                onClick={() => handleCopy(tags, "tags")}
                className="text-xs text-rose-400 hover:text-rose-300 font-semibold flex items-center gap-1 cursor-pointer"
              >
                {copiedSection === "tags" ? <Check className="w-3.5 h-3.5 text-emerald-400" /> : <Copy className="w-3.5 h-3.5" />}
                <span>{copiedSection === "tags" ? "Copied!" : "Copy All Tags"}</span>
              </button>
            </div>
            <input
              type="text"
              value={tags}
              onChange={(e) => setTags(e.target.value)}
              onBlur={handleSave}
              className="w-full px-3 py-2 bg-slate-900 border border-slate-800 rounded-xl text-slate-300 text-xs focus:outline-none focus:border-teal-400"
            />
          </div>

          {/* Viral Hashtags */}
          <div className="bg-slate-950/60 p-4 rounded-2xl border border-slate-800/80">
            <div className="flex items-center justify-between mb-2">
              <label className="text-xs font-bold uppercase tracking-wider text-slate-300 flex items-center gap-1.5">
                <Hash className="w-3.5 h-3.5 text-indigo-400" />
                <span>Viral Hashtags</span>
              </label>
              <button
                onClick={() => handleCopy(hashtags, "hashtags")}
                className="text-xs text-rose-400 hover:text-rose-300 font-semibold flex items-center gap-1 cursor-pointer"
              >
                {copiedSection === "hashtags" ? <Check className="w-3.5 h-3.5 text-emerald-400" /> : <Copy className="w-3.5 h-3.5" />}
                <span>{copiedSection === "hashtags" ? "Copied!" : "Copy Hashtags"}</span>
              </button>
            </div>
            <input
              type="text"
              value={hashtags}
              onChange={(e) => setHashtags(e.target.value)}
              onBlur={handleSave}
              className="w-full px-3 py-2 bg-slate-900 border border-slate-800 rounded-xl text-indigo-300 font-semibold text-xs focus:outline-none focus:border-indigo-400"
            />
          </div>
        </div>
      </div>
    </div>
  );
};
